export const PLANETS = [
  {
    name: "Mercury",
    color: "#A5A5A5",
    size: 0.4,
    distance: 4,
    speed: 0.04,
    description: "The smallest planet in our solar system and closest to the Sun.",
    temp: "167°C",
  },
  {
    name: "Venus",
    color: "#E3BB76",
    size: 0.9,
    distance: 7,
    speed: 0.015,
    description: "Spinning in the opposite direction to most planets, Venus is the hottest planet.",
    temp: "464°C",
  },
  {
    name: "Earth",
    color: "#2271B3",
    size: 1,
    distance: 10,
    speed: 0.01,
    description: "Our home planet is the only place we know of so far that’s inhabited by living things.",
    temp: "15°C",
  },
  {
    name: "Mars",
    color: "#E27B58",
    size: 0.5,
    distance: 13,
    speed: 0.008,
    description: "Mars is a dusty, cold, desert world with a very thin atmosphere.",
    temp: "-65°C",
  },
  {
    name: "Jupiter",
    color: "#D39C7E",
    size: 2.5,
    distance: 20,
    speed: 0.002,
    description: "Jupiter is more than twice as massive than the other planets of our solar system combined.",
    temp: "-110°C",
  },
  {
    name: "Saturn",
    color: "#C5AB6E",
    size: 2.1,
    distance: 26,
    speed: 0.0009,
    description: "Adorned with a dazzling, complex system of icy rings, Saturn is unique in our solar system.",
    temp: "-140°C",
    rings: true,
  },
  {
    name: "Uranus",
    color: "#B5E3E3",
    size: 1.8,
    distance: 32,
    speed: 0.0004,
    description: "Uranus is very cold and windy. The ice giant is surrounded by 13 faint rings.",
    temp: "-195°C",
  },
  {
    name: "Neptune",
    color: "#6081FF",
    size: 1.7,
    distance: 38,
    speed: 0.0001,
    description: "Dark, cold and whipped by supersonic winds, giant Neptune is the eighth and most distant planet.",
    temp: "-201°C",
  },
];
